import Vue from 'vue'
import { Button, Form, FormItem, Input, Message, Container, Header, Aside,Main, Footer,Menu ,MenuItem,MenuItemGroup,Submenu,Carousel,CarouselItem,PageHeader,link,Backtop,Row,Col,Card,MessageBox,Tabs,TabPane,RadioButton,RadioGroup,Dialog,Tooltip,Radio,Select,Option,Step,Steps,Divider,Table,TableColumn,Breadcrumb,BreadcrumbItem,Drawer,Tree,Notification,Pagination,Loading,ColorPicker,Switch} from 'element-ui'

Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Footer)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(Submenu)
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.use(PageHeader)
Vue.use(link)
Vue.use(Backtop)
Vue.use(Col)
Vue.use(Row)
Vue.use(Card)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(RadioButton)
Vue.use(RadioGroup)
Vue.use(Dialog)
Vue.use(Tooltip)
Vue.use(Radio)
Vue.use(Select)
Vue.use(Option)
Vue.use(Step)
Vue.use(Steps)
Vue.use(Divider)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Drawer)
Vue.use(Tree)
Vue.use(Pagination)
Vue.use(Loading)
Vue.use(ColorPicker)
Vue.use(Switch)
Vue.prototype.$message = Message
Vue.prototype.$messagebox = MessageBox
Vue.prototype.$notify = Notification