spring:
  datasource:
    username: root
    password: Kaimi1234/
    url: jdbc:mysql://localhost:3306/industrialplatform?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.industrialplatform.beta.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  port: 8888